# Generated by Django 4.1.2 on 2022-10-25 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('tags', models.TextField()),
                ('image', models.FileField(upload_to='pic/%y/')),
            ],
        ),
    ]
