# Generated by Django 4.1.2 on 2022-10-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.FileField(upload_to='pic/'),
        ),
    ]
